config/routes.rb
Rails.application.routes.draw do
  scope module: 'depp' do
    resources :domains do
      collection do
        post 'update', as: 'update'
        post 'destroy', as: 'destroy'
        get 'renew'
        match 'transfer', via: [:post, :get]
        get 'edit'
        get 'info'
        get 'check'
        get 'delete'
      end
    end

    resources :contacts do
      member do
        get 'delete'
        post 'fullshow' # a bit more secure than get for password field
        post 'fulledit' # a bit more secure than get for password field
      end

      collection do
        get 'check'
        get 'info'
      end
    end

    resource :poll do
      collection do
        post 'confirm_keyrelay'
        post 'confirm_transfer'
      end
    end

    resource :keyrelay

    resource :xml_console do
      collection do
        get 'load_xml'
      end
    end

    root 'polls#show'
  end

  resources :sessions do
    collection do
      post 'pki'
    end
  end

  get '/login', to: 'sessions#login', as: 'login'
  get '/logout', to: 'sessions#destroy'
end

app/models/depp/contact.rb
module Depp
  class Contact
    include ActiveModel::Model

    attr_accessor :id, :name, :email, :phone, :org_name,
      :ident, :ident_type, :ident_country_code,
      :street, :city, :zip, :state, :country_code,
      :password, :legal_document, :statuses, :code

    DISABLED = 'Disabled'
    DISCLOSURE_TYPES = [DISABLED, '1', '0']
    TYPES = %w( org priv birthday )
    SELECTION_TYPES = [
      ['Business code', 'org'],
      ['Personal identification code', 'priv'],
      ['Birthday', 'birthday']
    ]

    class << self
      attr_reader :epp_xml, :user

      # rubocop:disable Metrics/AbcSize
      def find_by_id(id, password = nil)
        data = info_xml(id, password)

        res = data.css('epp response resData infData')
        ext = data.css('epp response extension')
        new(
          id: res.css('id').text,
          code: res.css('id').text,
          email: res.css('email').text,
          phone: res.css('voice').text,
          ident: ext.css('ident').text,
          ident_type: ext.css('ident').first.try(:attributes).try(:[], 'type').try(:value),
          ident_country_code: ext.css('ident').first.try(:attributes).try(:[], 'cc').try(:value),

          # postalInfo
          name: res.css('postalInfo name').text,
          org_name: res.css('postalInfo org').text,

          # address
          street:       res.css('postalInfo addr street').text,
          city:         res.css('postalInfo addr city').text,
          zip:          res.css('postalInfo addr pc').text,
          state:        res.css('postalInfo addr sp').text,
          country_code: res.css('postalInfo addr cc').text,

          # authInfo
          password: res.css('authInfo pw').text,

          # statuses
          statuses: data.css('status').map { |s| [s['s'], s.text] }
        )
      end
      # rubocop:enable Metrics/AbcSize

      def user=(user)
        @user = user
        @epp_xml = EppXml::Contact.new(cl_trid_prefix: user.tag)
      end

      def info_xml(id, password = nil)
        xml = epp_xml.info(
          id: { value: id },
          authInfo: { pw: { value: password } }
        )
        user.request(xml)
      end

      def construct_check_hash_from_data(data)
        res = data.css('epp response resData chkData cd')
        @contacts = []
        res.each do |_r|
          id = res.css('id').try(:text)
          reason = res.css('reason').present? ? res.css('reason').text : I18n.t(:available)
          @contacts << { id: id, reason: reason  }
        end
        @contacts
      end

      def contact_id_from_xml(data)
        id = data.css('epp response resData creData id').text
        id.blank? ? nil : id
      end

      def construct_create_disclosure_xml(cph, flag)
        xml = { disclose: {} }
        cph.each do |k, v|
          xml[:disclose][k] = {}
          xml[:disclose][k][:value] = v
        end
        xml[:disclose][:attrs] = {}
        xml[:disclose][:attrs][:flag] = flag
        xml.with_indifferent_access
      end

      def extract_disclosure_hash(cpd) # cpd = contact_params[:disclose]
        return {} unless cpd
        cpd = cpd.delete_if { |k, v| v if v != '1' && k == 'flag' }
        cpd
      end

      def extract_info_disclosure(data)
        hash = {}
        data.css('disclose').each do |d|
          flag = d.attributes['flag'].value
          next unless flag
          hash[flag] = {}
          d.children.each do |c|
            hash[flag][c.name] = flag if %w( name email fax voice addr org_name ).include?(c.name)
          end
        end
        hash
      end

      def type_string(type_code)
        return '' if type_code.blank?
        t = SELECTION_TYPES.select { |tp| tp.second == type_code }
        t.try(:first).try(:first)
      end

      def check(id)
        xml = Depp::Contact.epp_xml.check(id: { value: id })
        Depp::Contact.user.request(xml)
      end
    end

    def save
      hash = {
        id: { value: code },
        postalInfo: {
          name: { value: name },
          org:  { value: org_name },
        },
        voice: { value: phone },
        email: { value: email }
      }

      address_provided = city.present? && country_code.present?

      if address_provided
        hash[:postalInfo][:addr] = {
          street: { value: street },
          city:   { value: city },
          sp:     { value: state },
          pc:     { value: zip },
          cc:     { value: country_code }
        }
      end

      hash[:id] = nil if code.blank?
      create_xml = Depp::Contact.epp_xml.create(hash, extension_xml)

      data = Depp::Contact.user.request(create_xml)
      self.id = data.css('id').text
      handle_errors(data)
    end

    # rubocop:disable Metrics/MethodLength
    # rubocop:disable Metrics/AbcSize
    def update_attributes(params)
      self.ident_country_code = params[:ident_country_code]
      self.ident_type   = params[:ident_type]
      self.ident        = params[:ident]

      self.name  = params[:name]
      self.email = params[:email]
      self.phone = params[:phone]

      self.org_name     = params[:org_name]
      self.street       = params[:street]
      self.city         = params[:city]
      self.zip          = params[:zip]
      self.state        = params[:state]
      self.country_code = params[:country_code]

      xml_data = {
        id: { value: id },
        chg: {
          postalInfo: {
            name: { value: name },
            org:  { value: org_name },
          },
          voice: { value: phone },
          email: { value: email },
          authInfo: {
            pw: { value: password }
          }
        }
      }

      address_provided = city.present? && country_code.present?

      if address_provided
        xml_data[:chg][:postalInfo][:addr] = {
          street: { value: street },
          city:   { value: city },
          sp:     { value: state },
          pc:     { value: zip },
          cc:     { value: country_code }
        }
      end

      update_xml = Depp::Contact.epp_xml.update(xml_data, extension_xml)
      data = Depp::Contact.user.request(update_xml)

      handle_errors(data)
    end
    # rubocop:enbale Metrics/AbcSize
    # rubocop:enable Metrics/MethodLength

    def delete
      delete_xml = Contact.epp_xml.delete(
        {
          id: { value: id },
          authInfo: { pw: { value: password } }
        },
        extension_xml
      )
      data = Depp::Contact.user.request(delete_xml)
      handle_errors(data)
    end

    def extension_xml
      xml = { _anonymus: [] }
      ident = ident_xml[:_anonymus].try(:first) unless persisted?
      legal = legal_document_xml[:_anonymus].try(:first)
      xml[:_anonymus] << ident if ident.present?
      xml[:_anonymus] << legal if legal.present?
      xml
    end

    def ident_xml
      {
        _anonymus: [
          ident: { value: ident, attrs: { type: ident_type, cc: ident_country_code } }
        ]
      }
    end

    def legal_document_xml
      return {} if legal_document.blank?

      type = legal_document.original_filename.split('.').last.downcase
      {
        _anonymus: [
          legalDocument: { value: Base64.encode64(legal_document.read), attrs: { type: type } }
        ]
      }
    end

    def check(id)
      xml = epp_xml.check(id: { value: id })
      current_user.request(xml)
    end

    def country_name
      Country.new(country_code)
    end

    def org?
      ident_type == 'org'
    end

    def priv?
      ident_type == 'priv'
    end

    def persisted?
      id.present?
    end

    def complete_info?
      email.present?
    end

    def handle_errors(data)
      data.css('result').each do |x|
        success_codes = %(1000, 1300, 1301)
        next if success_codes.include?(x['code'])

        message = "#{x.css('msg').text} #{x.css('value').text}"
        attr = message.split('[').last.strip.sub(']', '') if message.include?('[')
        attr = :base if attr.nil?
        attr = 'phone' if attr == 'voice'
        attr = 'zip' if attr == 'pc'
        errors.add(attr, message)
      end
      errors.blank?
    end
  end
end

app/controllers/depp/contacts_controller.rb
module Depp
  class ContactsController < ApplicationController
    before_action :init_epp_contact

    def index
      limit, offset = pagination_details

      res = depp_current_user.repp_request('contacts', { details: true, limit: limit, offset: offset })
      flash.now[:epp_results] = [{ 'code' => res.code, 'msg' => res.message }]
      return redirect_to login_path, alert: "#{res.message} [#{res.code}]" if res.code != '200'

      @response = res.parsed_body.with_indifferent_access if res.code == '200'
      @contacts    = @response ? @response[:contacts] : []

      @paginatable_array = Kaminari.paginate_array(
        [], total_count: @response[:total_number_of_records]
      ).page(params[:page]).per(limit)
    end

    def new
      @contact = Depp::Contact.new
    end

    def show
      @contact = Depp::Contact.find_by_id(params[:id])
      if params[:com] == 'update' && @contact.complete_info?
        return redirect_to edit_contact_path(params[:id])
      end
    end

    def fullshow
      @contact = Depp::Contact.find_by_id(params[:id], params[:password])
      render 'show'
    end

    def edit
      @contact = Depp::Contact.find_by_id(params[:id])
    end

    def fulledit
      @contact = Depp::Contact.find_by_id(params[:id], params[:password])
      if @contact.persisted? && @contact.complete_info?
        render 'edit'
      else
        redirect_to :back, notice: I18n.t(:wrong_password)
      end
    end

    def create
      @contact = Depp::Contact.new(params[:depp_contact])

      if @contact.save
        redirect_to contact_url(@contact.id)
      else
        render 'new'
      end
    end

    def update
      @contact = Depp::Contact.new(params[:depp_contact])

      if @contact.update_attributes(params[:depp_contact])
        redirect_to contact_url(@contact.id)
      else
        render 'edit'
      end
    end

    def delete
      @contact = Depp::Contact.find_by_id(params[:id])
    end

    def destroy
      @contact = Depp::Contact.new(params[:depp_contact])

      if @contact.delete
        redirect_to contacts_url, notice: t(:destroyed)
      else
        render 'delete'
      end
    end

    def info
      if params[:contact_id]
        if params[:com] == 'delete'
          redirect_to delete_contact_path(params[:contact_id], com: params[:com])
        else
          redirect_to contact_path(params[:contact_id], com: params[:com])
        end
      else
        render 'info_index'
      end
    end

    def check
      if params[:contacts].present?
        @ids = params[:contacts]
        # if @ids
          # @contacts = []
          # @ids.split(',').each do |id|
            # @contacts << id.strip
          # end
        # end
        return unless @ids

        @data = Depp::Contact.check(@ids)
        @contacts = Depp::Contact.construct_check_hash_from_data(@data)
      else
      end
    end

    private

    def init_epp_contact
      Depp::Contact.user = depp_current_user
    end
  end
end

app/controllers/depp/domains_controller.rb
module Depp
  class DomainsController < ApplicationController
    before_action :init_domain, except: :new

    def index
      limit, offset = pagination_details

      res = depp_current_user.repp_request('domains', { details: true, limit: limit, offset: offset })
      flash.now[:epp_results] = [{ 'code' => res.code, 'msg' => res.message }]
      return redirect_to login_path, alert: "#{res.message} [#{res.code}]" if res.code != '200'

      @response = res.parsed_body.with_indifferent_access 
      @contacts = @response ? @response[:contacts] : []

      @paginatable_array = Kaminari.paginate_array(
        [], total_count: @response[:total_number_of_records]
      ).page(params[:page]).per(limit)
    end

    def info
      if params[:domain_name]
        case params[:com]
        when 'delete'
          redirect_to delete_domains_path(domain_name: params[:domain_name])
        when 'update'
          redirect_to edit_domains_path(domain_name: params[:domain_name])
        else
          @data = @domain.info(params[:domain_name])
          render 'info_index' and return unless response_ok?
        end
      else
        render 'info_index'
      end
    end

    def check
      if params[:domain_name]
        @data = @domain.check(params[:domain_name])
        render 'check_index' and return unless response_ok?
      else
        render 'check_index'
      end
    end

    def new
      @domain_params = Depp::Domain.default_params
    end

    def create
      @domain_params = params[:domain]
      @data = @domain.create(@domain_params)

      if response_ok?
        redirect_to info_domains_path(domain_name: @domain_params[:name])
      else
        render 'new'
      end
    end

    def edit
      @data = @domain.info(params[:domain_name])
      @domain_params = Depp::Domain.construct_params_from_server_data(@data)
    end

    def update
      @domain_params = params[:domain]
      @data = @domain.update(@domain_params)

      if response_ok?
        redirect_to info_domains_path(domain_name: @domain_params[:name])
      else
        params[:domain_name] = @domain_params[:name]
        render 'new'
      end
    end

    def delete; end

    def destroy
      @data = @domain.delete(params[:domain])
      @results = @data.css('result')
      if response_ok?
        params[:domain_name] = nil
        render 'info_index'
      else
        params[:domain_name] = params[:domain][:name]
        render 'delete'
      end
    end

    def renew
      if params[:domain_name] && params[:cur_exp_date]
        @data = @domain.renew(params)
        render 'renew_index' and return unless response_ok?
      else
        render 'renew_index'
      end
    end

    def transfer
      if params[:domain_name]
        @data = @domain.transfer(params)
        render 'transfer_index' and return unless response_ok?
      else
        render 'transfer_index'
      end
    end

    private

    def init_domain
      @domain = Depp::Domain.new(current_user: depp_current_user)
    end
  end
end

app/controllers/depp/keyrelays_controller.rb
module Depp
  class KeyrelaysController < ApplicationController
    def show; end

    def create
      keyrelay = Depp::Keyrelay.new(current_user: depp_current_user)
      @data = keyrelay.keyrelay(params)

      if response_ok?
        flash[:epp_results] = [{ 'code' => '1000', 'msg' => 'Command completed successfully' }]
        redirect_to keyrelay_path
      else
        render 'show'
      end
    end
  end
end

app/controllers/depp/polls_controller.rb
module Depp
  class PollsController < ApplicationController
    before_action :init_epp_xml

    def show
      @data = depp_current_user.request(@ex.poll)
    end

    def destroy
      @data = depp_current_user.request(@ex.poll(poll: {
        value: '', attrs: { op: 'ack', msgID: params[:id] }
      }))

      @results = @data.css('result')

      @data = depp_current_user.request(@ex.poll)
      render 'show'
    end

    def confirm_keyrelay
      domain_params = params[:domain]
      @data = @domain.confirm_keyrelay(domain_params)

      if response_ok?
        redirect_to info_domains_path(domain_name: domain_params[:name])
      else
        @results = @data.css('result')
        @data = depp_current_user.request(@ex.poll)
        render 'show'
      end
    end

    def confirm_transfer
      domain_params = params[:domain]
      @data = @domain.confirm_transfer(domain_params)

      @results = @data.css('result')
      @data = depp_current_user.request(@ex.poll)

      render 'show'
    end

    private

    def init_epp_xml
      @ex = EppXml::Session.new(cl_trid_prefix: depp_current_user.tag)
      @domain = Depp::Domain.new(current_user: depp_current_user)
    end
  end
end

app/controllers/depp/xml_consoles_controller.rb
module Depp
  class XmlConsolesController < ApplicationController
    def show; end

    def create
      begin
        @result = depp_current_user.server.request(params[:payload])
      rescue
        @result = 'CONNECTION ERROR - Is the EPP server running?'
      end
      render :show
    end

    def load_xml
      # binding.pry
      cl_trid = "#{depp_current_user.tag}-#{Time.now.to_i}"
      xml_dir_path = Rails.root + 'app/views/depp/xml_consoles/epp_requests'
      xml = File.read("#{xml_dir_path}/#{params[:obj]}/#{params[:epp_action]}.xml")
      xml.gsub!('<clTRID>ABC-12345</clTRID>', "<clTRID>#{cl_trid}</clTRID>")
      render text: xml
    end
  end
end

app/views/depp/domains/_check_form.haml
= form_tag check_domains_path, class: 'form-horizontal', method: :get do
  .form-group
    .col-md-3.control-label
      = label_tag :domain_name, t(:domain_name)
    .col-md-7
      = text_field_tag :domain_name, params[:domain_name], class: 'form-control'
    .col-md-2
      %button.btn.btn-primary
        &nbsp;
        %span.glyphicon.glyphicon-search
        &nbsp;

app/views/depp/domains/_form.haml
- path = (params[:domain_name]) ? update_domains_path : domains_path
= form_tag(path, class: 'form-horizontal', multipart: true) do
  .row
    .col-md-12
      / Nav tabs
      %ul.nav.nav-tabs{:role => "tablist", id: 'tabs'}
        %li.active
          %a{"data-toggle" => "tab", :href => "#general-tab", :role => "tab"}= t('general')
      / Tab panes
      .tab-content
        #general-tab.tab-pane.active
          = render 'depp/domains/form_partials/general'
          = render 'depp/domains/form_partials/contacts'
          %hr
          = render 'depp/domains/form_partials/nameservers'
          %hr
          = render 'depp/domains/form_partials/dnskeys'

        .panel.panel-default
          .panel-heading.clearfix
            .pull-left= t(:legal_document)
          .panel-body
            .form-group
              = label_tag 'domain[legal_document]', t('legal_document'),class: 'col-md-3 control-label'
              .col-md-9
                = file_field_tag 'domain[legal_document]'

  .row
    .col-md-12.text-right
      = button_tag(t('shared.save'), class: 'btn btn-primary')

:javascript
  $(function () {
    $('#tabs a:first').tab('show')
  })

app/views/depp/domains/check.haml
= render 'depp/shared/title', name: t(:check_domain)

.row
  .col-md-12
    = render 'check_form'

%hr

.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        %h3.panel-title= t('result')
      .panel-body
        %dl.dl-horizontal
          %dt= t('name')
          %dd= @data.css('name').text

          - name = @data.css('name').first
          %dt= t('available')
          %dd= name['avail']

          - if @data.css('reason').text.present?
            %dt= t('reason')
            %dd= @data.css('reason').text

app/views/depp/domains/check_index.haml
= render 'depp/shared/title', name: t(:check_domain)

.row
  .col-md-12
    = render 'check_form'

app/views/depp/domains/delete.haml
= render 'depp/shared/title', name: "#{t(:delete)}: #{params[:domain_name]}"

= form_tag(destroy_domains_path, class: 'form-horizontal', multipart: true, method: :delete) do
  .panel.panel-default
    .panel-heading.clearfix
      = t(:legal_document)
    .panel-body
      .form-group
        .col-md-4.control-label
          = label_tag 'domain[verified]', t('verified')
        .col-md-6
          = check_box_tag 'domain[verified]', '1', params[:verified].eql?('1'), onclick: "return (confirm('#{t(:verified_confirm)}') ? true : false);"

      .form-group
        .col-md-4.control-label
          = label_tag 'domain[legal_document]', t('legal_document')
        .col-md-6
          = file_field_tag 'domain[legal_document]'
          = hidden_field_tag 'domain[name]', params[:domain_name]
  %hr
  .row
    .col-md-12.text-right
      = button_tag t('delete'), class: 'btn btn-danger'

app/views/depp/domains/edit.haml
= render 'depp/shared/title', name: "#{t(:edit)}: #{params[:domain_name]}"

%hr
= render 'form'

app/views/depp/domains/index.haml
- content_for :actions do
  = link_to(t(:new), new_domain_path, class: 'btn btn-primary')
  = link_to(t(:transfer), transfer_domains_path, class: 'btn btn-default')
  -# = link_to(t(:keyrelay), keyrelay_path, class: 'btn btn-default')
= render 'depp/shared/title', name: t(:domains)

.row
  .col-md-12{style: 'margin-bottom: -15px;'}
    = form_tag info_domains_path, class: 'form-horizontal', method: :get do
      .col-md-11
        .form-group
          = text_field_tag :domain_name, params[:domain_name], class: 'form-control', placeholder: t('domain_name'), autocomplete: 'off', autofocus: true
      .col-md-1.text-right.text-center-xs
        .form-group
          %button.btn.btn-primary
            &nbsp;
            %span.glyphicon.glyphicon-search
            &nbsp;

%hr

- if @response
  .panel.panel-default
    .table-responsive
      %table.table.table-hover.table-bordered.table-condensed.domify
        %thead
          %tr
            %th{class: 'col-xs-3'}= t(:name)
            %th{class: 'col-xs-6'}= t(:valid)
            %th{class: 'col-xs-3'}= t(:actions)
        %tbody
          - @response['domains'].each do |x|
            %tr
              %td= link_to(x['name'], info_domains_path(domain_name: x['name']))
              %td
                = Time.parse(x['valid_from']).try(:to_date)
                \-
                = Time.parse(x['valid_to']).try(:to_date)
              %td
                = link_to(t(:edit), edit_domains_path(domain_name: x['name']),
                  class: 'btn btn-primary btn-xs')
                = link_to(t(:renew), renew_domains_path(domain_name: x['name']),
                  class: 'btn btn-default btn-xs')
                = link_to(t(:delete), delete_domains_path(domain_name: x['name']),
                  class: 'btn btn-default btn-xs')

= paginate @paginatable_array

app/views/depp/domains/info.haml
- content_for :actions do
  = link_to(t(:edit), edit_domains_path(domain_name: params[:domain_name]), 
    class: 'btn btn-primary')
  = link_to(t(:renew), renew_domains_path(domain_name: params[:domain_name]), 
    class: 'btn btn-default') 
  = link_to(t(:delete), delete_domains_path(domain_name: params[:domain_name]), 
    class: 'btn btn-default')
= render 'depp/shared/title', name: truncate(@data.css('name').text)

.row
  .col-sm-12
    - if @data.css('result').first['code'] == '1000'
      .row
        .col-md-12= render 'depp/domains/partials/general'
      .row
        .col-md-12= render 'depp/domains/partials/contacts'
      .row
        .col-md-12= render 'depp/domains/partials/statuses'
      .row
        .col-md-12= render 'depp/domains/partials/nameservers'
      .row
        .col-md-12= render 'depp/domains/partials/dnskeys'
    - else
      .row
        .col-sm-6
          %h1= t(:not_found)

app/views/depp/domains/info_index.haml
- title = t(:domain_info)
- title = t(:delete_domain) if params[:com] == 'delete'
- title = t(:update_domain) if params[:com] == 'update'
= render 'depp/shared/title', name: title

.row
  .col-md-12
    = form_tag info_domains_path, class: 'form-horizontal', method: :get do
      = hidden_field_tag :com, params[:com]
      .form-group
        .col-md-3.control-label
          = label_tag :domain_name, t(:domain_name)
        .col-md-7
          = text_field_tag :domain_name, params[:domain_name], class: 'form-control', autofocus: true
        .col-md-2
          %button.btn.btn-primary
            &nbsp;
            %span.glyphicon.glyphicon-search
            &nbsp;

app/views/depp/domains/new.haml
= render 'depp/shared/title', name: t(:new_domain)

= render 'form'

app/views/depp/domains/renew.haml
= render 'depp/shared/title', name: t(:renew_domain)

.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        %h3.panel-title= t('result')
      .panel-body
        %dl.dl-horizontal
          %dt= t('domain_name')
          %dd= @data.css('name').text

          %dt= t('valid_to')
          %dd= @data.css('exDate').text

app/views/depp/domains/renew_index.haml
= render 'depp/shared/title', name: t(:renew_domain)

.row
  .col-md-12
    = form_tag renew_domains_path, class: 'form-horizontal', method: :get do
      .form-group
        = label_tag :domain_name, t('name'), class: 'col-md-2 control-label'
        .col-md-10
          = text_field_tag :domain_name, params[:domain_name], class: 'form-control', placeholder: t('domain_name'), autocomplete: 'off'
      .form-group
        = label_tag :cur_exp_date, t('cur_exp_date'), class: 'col-md-2 control-label'
        .col-md-10
          = text_field_tag :cur_exp_date, params[:cur_exp_date], class: 'form-control', placeholder: 'yyyy-mm-dd', autocomplete: 'off'
      .form-group
        = label_tag :domain_period, t('period'), class: 'col-md-2 control-label'
        .col-md-5
          = text_field_tag(:period, params[:period], class: 'form-control')
        .col-md-5
          = select_tag :period_unit, options_for_select(['y', 'm', 'd'], params[:period_unit]), { class: 'form-control' }
      .form-group
        .col-md-offset-2.col-md-10
          %button.btn.btn-primary= t('renew')

app/views/depp/domains/transfer.haml
= render 'depp/shared/title', name: t(:transfer_domain)

.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        %h3.panel-title= t('result')
      .panel-body
        %dl.dl-horizontal
          %dt= t('domain_name')
          %dd= @data.css('name').text

          - @data.css('trnData').children.each do |x|
            - next if x.blank?
            %dt= t(x.name)
            %dd= x.text

app/views/depp/domains/transfer_index.haml
= render 'depp/shared/title', name: t(:transfer_domain)

.row
  .col-md-12
    = form_tag transfer_domains_path, class: 'form-horizontal', method: :post, multipart: true do
      .form-group
        = label_tag :domain_name, t('name'), class: 'col-md-2 control-label'
        .col-md-10
          = text_field_tag :domain_name, params[:domain_name], class: 'form-control', placeholder: t('domain_name'), autocomplete: 'off', autofocus: true
      .form-group
        = label_tag :password, t('password'), class: 'col-md-2 control-label'
        .col-md-10
          = text_field_tag :password, params[:password], class: 'form-control', autocomplete: 'off'
      .form-group
        = label_tag 'legal_document', t('legal_document'),class: 'col-md-2 control-label'
        .col-md-10
          = file_field_tag 'legal_document'
      .form-group
        .col-md-offset-2.col-md-10
          %button.btn.btn-primary{ name: 'request' }= t('transfer')
          -# %button.btn.btn-primary{ name: 'approve' }= t('approve')
          -# %button.btn.btn-primary{ name: 'reject' }= t('reject')